import { Injectable } from '@angular/core';
import { getAllDebugNodes } from '@angular/core/src/debug/debug_node';

/*
  Generated class for the ServiceDataProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class ServiceDataProvider {

  public cards: any = [];


  constructor() {
    this.cards = [
      { 
        isShown:false, 
        title: "Bumétanide (Burinex®)", 
        AMM:"", 
        indication: "HTA", 
        indication1: "Insuff. card.",
        classeMed: "Diurétique (anse)", 
        voieAdmin: "PO", 
        voieAdmin1: "IV",      
        presentation: "BUMETANIDE 1 mg cp",
        presentation1: "BUMETANIDE 2 mg/4 ml sol inj",
        posologie: "10 µg/kg/h", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVSE", 
        remarques:"possibilité  de doubler si insuffisant",
        lien: "https://www.vidal.fr/medicaments/substances/bumetanide-670.html",
      },

      { 
        isShown:false, 
        title: "Furosémide (Lasilix®)", 
        AMM:"max. 4 mg/kg/jg", 
        indication: "HTA", 
        indication1: "Insuff. card.",
        classeMed: "Diurètique (anse)", 
        voieAdmin: "IV",
        voieAdmin1: "PO",        
        presentation: "FUROSEMIDE 20 mg cp ou 10 mg/mL sol pr perf",
        posologie: "1 mg/kg", 
        reconstitution: "", 
        dilution: "Serum physiologique", 
        administration:"PO ou IVL", 
        remarques:"ne pas dépasser 4 prises par jour",
        lien: "https://www.vidal.fr/medicaments/substances/furosemide-1579.html",
      },

      
      { 
        isShown:false, 
        title: "Enalapril (Renitec®)", 
        AMM:"", 
        indication: "HTA", 
        classeMed: "Inhibiteur ECA", 
        voieAdmin: "PO",       
        presentation: "ENALAPRIL MALEATE 5 mg cp",
        posologie: "25 µg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"PO en 2 prises", 
        remarques:"ne pas dépasser 5 mg/j",
        lien: "https://www.vidal.fr/medicaments/substances/enalapril-6771.html",
      },

      { 
        isShown:false, 
        title: "Labétolol (Trandate®)", 
        AMM:"", 
        indication: "HTA", 
        classeMed: "β-bloquant", 
        voieAdmin: "IV",       
        presentation: "LABETALOL CHLORHYDRATE 5 mg/ml sol inj",
        posologie: "0,3 mg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVL", 
        remarques:"Administration IVSE possible 2 mg/kg/j",
        lien: "https://www.vidal.fr/medicaments/substances/labetalol-6535.html",
      },

      { 
        isShown:false, 
        title: "Acebutolol (Sectral®)", 
        AMM:"", 
        indication: "HTA", 
        classeMed: "β-bloquant", 
        voieAdmin: "PO",       
        presentation: "ACEBUTOLOL (chlorhydrate) 200 mg cp",
        posologie: "1 mg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"PO en 2 prises par jour", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/substances/acebutolol-4283.html",
      },


      { 
        isShown:false, 
        title: "Nicardipine (Loxen®)", 
        AMM:"", 
        indication: "HTA", 
        classeMed: "Anti-calcique", 
        voieAdmin: "IV",       
        presentation: "NICARDIPINE CHLORHYDRATE 1 mg/ml sol p perf",
        posologie: "60 µg/kg/h", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVSE", 
        remarques:"possibilité d'augmenter jusqu'à 120 µg/kg/h si insuffisant",
        lien: "https://www.vidal.fr/medicaments/substances/nicardipine-6838.html",
      },

      { 
        isShown:false, 
        title: "Lévétiracetam (Keppra®)", 
        AMM:"", 
        indication: "Epilepsie", 
        classeMed: "Anti-épileptique", 
        voieAdmin: "PO",       
        presentation: "LEVETIRACETAM 250 mg cp",
        posologie: "30 mg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"PO toutes les 12h", 
        remarques:"ne pas dépasser 2g/j",
        lien: "https://www.vidal.fr/medicaments/gammes/levetiracetam-eg-61517.html",
      },

      { 
        isShown:false, 
        title: "Phénytoïne (Dilantin®)", 
        AMM:"", 
        indication: "Epilepsie", 
        classeMed: "Anti-épileptique", 
        voieAdmin: "IV",       
        presentation: "PHENYTOINE SODIQUE 50 mg/ml sol inj (DILANTIN)",
        posologie: "20 mg/kg/prise", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVL sur 20 minutes", 
        remarques:"ne pas dépasser 1500 mg/administration",
        lien: "https://www.vidal.fr/medicaments/dilantin-250-mg-5-ml-sol-inj-5235.html",
      },

      { 
        isShown:false, 
        title: "Phénobarbital (Gardénal®)", 
        AMM:"", 
        indication: "Epilepsie", 
        classeMed: "Barbiturique", 
        voieAdmin: "IV",       
        presentation: "PHENOBARBITAL (sodique) 40 mg/2 ml pdre/solv p sol inj",
        posologie: "15 mg/kg/prise", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVL sur 20 minutes", 
        remarques:"ne pas dépasser 500 mg/administration",
        lien: "https://www.vidal.fr/medicaments/substances/phenobarbital-2729.html",
      },

      { 
        isShown:false, 
        title: "Clonazépam (Rivotril®)", 
        AMM:"", 
        indication: "Epilepsie", 
        indication1: "Intox. AL",
        classeMed: "Benzodiazépine", 
        voieAdmin: "IV",       
        presentation: "CLONAZEPAM 1 mg/1 ml sol diluer/solv p sol inj",
        posologie: "Crise convulsive 20 µg/kg, IAL 15 µg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVD", 
        remarques:"Renouvelable 2 fois ou administrable IVSE 20 µg/kg/6h",
        lien: "https://www.vidal.fr/medicaments/substances/clonazepam-4157.html",
      },

      { 
        isShown:false, 
        title: "Terbutaline (Bricanyl®)", 
        AMM:"", 
        indication: "Asthme aigu grave", 
        classeMed: "β2-agoniste MD", 
        voieAdmin: "nébulisation",       
        presentation: "BRICANYL 5 mg/2 ml sol p inhal p nébulis en récipient unidose",
        posologie: "0,2 mg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"aérosol", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/bricanyl-5-mg-2-ml-sol-p-inhal-p-nebulis-en-recipient-unidose-2493.html",
      },

      { 
        isShown:false, 
        title: "Ipratropium (Atrovent®) aérosol", 
        AMM:"", 
        indication: "Asthme aigu grave", 
        classeMed: "Anticholinergique", 
        voieAdmin: "nébulisation",       
        presentation: "ATROVENT 0,50 mg/2 ml sol p inhal p nébulis",
        posologie: "0,25 à 0,5mg", 
        reconstitution: "", 
        dilution: "", 
        administration:"aérosol", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/atrovent-0-50-mg-2-ml-sol-p-inhal-p-nebulis-en-recipient-unidose-adulte-1705.html",
      },

      { 
        isShown:false, 
        title: "Methylprednisolone (Solumédrol®)", 
        AMM:"", 
        indication: "Anaphylaxie", 
        indication1: "AAG",
        classeMed: "Corticoïde", 
        voieAdmin: "IV",       
        presentation: "SOLUMEDROL 1 g pdre/solv p sol inj",
        posologie: "Anaphylaxie 1 mg/kg, Asthme aigu grave 2 mg/kg", 
        reconstitution: "Serum physiologique", 
        dilution: "", 
        administration:"IVD", 
        remarques:"Dans l'AAG, entretien 0,5 mg/kg/6h au décours",
        lien: "https://www.vidal.fr/medicaments/solumedrol-1-g-pdre-solv-p-sol-inj-15189.html",
      },

      { 
        isShown:false, 
        title: "Salbutamol aérosol (Ventoline®)", 
        AMM:"", 
        indication: "Asthme aigu", 
        classeMed: "β2-agoniste CD", 
        voieAdmin: "nébulisation",       
        presentation: "2,5 mg/2,5 ml sol p inhal p nébulis",
        posologie: "2,5 à 5mg", 
        reconstitution: "", 
        dilution: "", 
        administration:"aérosol", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/ventoline-2-5-mg-2-5-ml-sol-p-inhal-p-nebulis-en-recipient-unidose-17379.html",
      },

      { 
        isShown:false, 
        title: "Dantrolène (Dantrium®)", 
        AMM:"", 
        indication: "HTM", 
        classeMed: "Myorelaxant", 
        voieAdmin: "IV",       
        presentation: "DANTROLENE SODIQUE 20 mg pdre p sol inj",
        posologie: "2,5 mg/kg", 
        reconstitution: "utiliser de l'EPPI", 
        dilution: "1 ampoule dans 60 mL d'EPPI", 
        administration:"IVL", 
        remarques:"Après reconstitution, conserver à l'abri de la lumière et utiliser dans les 6h",
        lien: "https://www.vidal.fr/medicaments/dantrium-intraveineux-lyoph-p-us-parenter-4780.html",
      },

      { 
        isShown:false, 
        title: "Amiodarone (Cordarone®)", 
        AMM:"", 
        indication: "ACR", 
        classeMed: "Anti-arythmique", 
        voieAdmin: "IV",       
        presentation: "CORDARONE 150 mg/3 ml sol inj en ampoule IV",
        posologie: "5 mg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVD", 
        remarques:"Renouvelable après 5 minutes",
        lien: "https://www.vidal.fr/medicaments/cordarone-150-mg-3-ml-sol-inj-en-ampoule-iv-4468.html",
      },

      { 
        isShown:false, 
        title: "Adrénaline", 
        AMM:"", 
        indication: "ACR",
        indication1: "Anaphylaxie", 
        classeMed: "αβ-agoniste", 
        voieAdmin: "IV",       
        presentation: "ADRENALINE 1 mg/ml sol inj",
        posologie: "ACR 10 µg/kg, Anaphylaxie 1 µg/kg", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVD", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/substances/adrenaline-1356.html",
      },

      { 
        isShown:false, 
        title: "Noradrenaline", 
        AMM:"", 
        indication: "Vasoplégie", 
        classeMed: "α-agoniste", 
        voieAdmin: "IV",       
        presentation: "Noradrénaline ",
        posologie: "Protocole (cf. Urgences)", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVSE", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/substances/noradrenaline-7019.html",
      },
      
      { 
        isShown:false, 
        title: "Voriconazole (Vfend®)", 
        AMM:"", 
        indication: "Antifongique", 
        classeMed: "Azolés ", 
        voieAdmin: "IV",       
        presentation: "VORICONAZOLE 200 mg pdre p sol p perf",
        posologie: "2 à 12 ans et < 50 kg : 18 mg/kg/j à J1 puis 16 mg/kg/j. Après 12 ans et > 50 kg, 12 mg/kg/j à J1 puis 8 mg/kg/j. En 2 prises.", 
        reconstitution: "EPPI ou NaCl 0,9%, 19 mL pour obtenir 10 mg/mL.", 
        dilution: "G5% ou NaCl 0,9%, 0,5 à 5 mg/mL.", 
        administration:"IVL en 1 à 3h, sans dépasser 3 mg/kg/h.", 
        remarques:"Risque d'accumulation de l'excipient chez l'insuffisant rénal : préférer la forme orale chaque fois que possible. Incompatible avec la nutrition parentérale et les bicarbonates.",
        lien: "https://www.vidal.fr/medicaments/substances/voriconazole-21915.html",
      },
      

      {  
        isShown: false, 
        title: "Aciclovir (Zovirax®)", 
        AMM: "",
        indication: "Antiviral", 
        classeMed: "Anti-HHV", 
        voieAdmin: "IV", 
        presentation: "ZOVIRAX 250 mg pdre p sol inj IV", 
        posologie: "30 à 60 mg/kg/j en 3 prises.", 
        reconstitution: "avec EPPI ou NaCl 0,9%, 25 mg/mL.", 
        dilution: "NaCl 0,9%, max. 7 mg/mL sur VVP, 25 mg/mL sur VVC.", 
        administration:"IVL sur 60 minutes.", 
        remarques:"Incompatible avec la nutrition parentérale et la ceftazidime.",
        lien: "https://www.vidal.fr/medicaments/gammes/aciclovir-mylan-40986.html",
      },
      { 
        isShown: false,
        title: "Amikacine (Amiklin®)",
        AMM: "",
        indication: "Antibiothérapie", 
        classeMed: "Aminoside", 
        voieAdmin: "IV", 
        presentation: "Amikacine 2,5 à 10 mg/mL sol p perf",
        posologie: "15 à 30 mg/kg/j en 1 prise.", 
        reconstitution: "", 
        dilution: "si besoin, avec EPPI, 125 mg/mL.", 
        administration:"IV en 30 minutes.", 
        remarques:"Objectif : pic 60 à 80 mg/L ; résiduelle inférieure à 4 mg/L. Utiliser une ligne dédiée, ne pas mélanger avec béta-lactamines, héparines, dexaméthasone.",
        lien: "https://www.vidal.fr/medicaments/substances/amikacine-6676.html",
      },

      { 
        isShown: false,
        title: "Amoxicilline (Clamoxyl®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "",
        posologie: "100 à 200 mg/kg/j en 3 à 4 prises.", 
        reconstitution: "Avec EPPI, 50 mg/mL.", 
        dilution: "NaCl 0,9% (stable 6h) ou G5% (stable 1h), sans dépasser 100 mg/mL", 
        administration:"IVL en 30 à 60 minutes.", 
        remarques:"Ne pas mélanger avec les aminosides. Compatible en Y avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/substances/amoxicilline-310.html",
      },

      { 
      isShown:false, 
      title: "Amoxicilline + Acide Clavulanique (Augmentin®)", 
      AMM:"", 
      indication: "Antibiothérapie", 
      classeMed: "β-lactamine", 
      voieAdmin: "IV",       
      presentation: "",
      posologie: "Avant 3 mois ou 4kg, 100 mg/kg/j en 2 prises. > 3 mois mais < 40 kg, 150 mg/kg/j en 3 prises. Ensuite, posologies adulte.", 
      reconstitution: "EPPI ou NaCl 0,9%, 50 mg/mL.", dilution: "NaCl 0,9% (stable 1h) ou G5% (stable 30 minutes).", 
      administration:"IVL en 30 à 40 minutes. Jamais en moins de 5 minutes avant 3 mois.", 
      remarques:"Attention, posologies et concentrations exprimées en Amoxicilline, veiller à ne pas dépasser la dose d'acide clavulanique maximale de 20 mg/kg/j. Incompatible avec les aminosides. Compatible en Y avec l'alimentation parentérale.",
      lien: "https://www.vidal.fr/medicaments/gammes/augmentin-784.html", 
    },

      { 
        isShown:false, 
        title: "Amphotéricine B liposomale (Ambisome®, Fungizone®)", 
        AMM:"", 
        indication: "Antifongique", 
        classeMed: "Antiparasitaire", 
        voieAdmin: "IV",       
        presentation: "AMPHOTERICINE B (liposomale) 50 mg pdre p dispers p perf",
        posologie: "3 mg/kg/j en 1 prise.", 
        reconstitution: "Flacon de 50 mg avec 12 mL d'EPPI pour obtenir une solution-mère à 4 mg/mL.", 
        dilution: "Dans du G5% - jamais dans du NaCl 0,9%. Entre 0,2 et 2 mg/mL. Utiliser le filtre de 5 µm pour mettre la solution reconstituée dans le G5% de dilution.", 
        administration:"IV en 30 à 60 minutes.", 
        remarques:"Filtre à 5 µm livré dans l'emballage, à utiliser pour rettenir d'éventuels agglomérats de liposomes qui se seraient formés pendant la reconstitution, en cas d'agitation insuffisante. Attention, incompatible avec le NaCl, les électrolytes et la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/substances/amphotericine-b-314.html",
      },

      
      {       
        isShown:false, 
        title: "Caspofungine (Cancidas®)", 
        AMM:"", 
        indication: "Antifongique", 
        classeMed: "Échinocandines", 
        voieAdmin: "IV",       
        presentation: "CASPOFUNGINE (acétate) 50 mg pdre p sol diluer p perf ",
        posologie: "70 mg/m²/j à J1, puis 50 mg/m²/j, en 1 prise.", 
        reconstitution: "Flacon de 50 mg avec 10,5 mL d'EPPI pour obtenir une solution mère à 5,2 mg/mL ou flacon de 70 mg avec 10,5 mL d'EPPI pour obtenir une solution-mère à 7,6 mg/mL.", 
        dilution: "NaCl 0,9% (jamais dans du G5%). Max 0,5 mg/mL. Utiliser pur non dilué si restriction hydrique et VVC.", 
        administration:"IVL en 60 minutes", 
        remarques:"Incompatible avec le glucose, la nutrition parentérale et l'héparine.",
        lien: "https://www.vidal.fr/medicaments/substances/caspofungine-21849.html",
      },
    
        { 
        isShown:false, 
        title: "Céfamandole", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "C2G", 
        voieAdmin: "IV",       
        presentation: "CEFAMANDOLE (nafate) 750 mg pdre p sol inj",
        posologie: "150 mg/kg/j en 3 à 6 prises, max. 6 g/j", 
        reconstitution: "Flacon de 750 mg avec 10 mL d'EPPI, de G5% ou de NaCl 0,9%.", 
        dilution: "Si besoin dans EPPI, NaCl 0,9% ou G5%, pas de concentration cible.", 
        administration:"IVL en 30 minutes.", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/substances/cefamandole-853.html",
      },
     
        { 
        isShown:false, 
        title: "Céfépime (Axepim®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "C4G", 
        voieAdmin: "IV",       
        presentation: "CEFEPIME (chlorhydrate) 500 mg pdre p sol inj",
        posologie: "150 mg/kg/j en 3 prises, max 6 g/j", 
        reconstitution: "EPPI, G5% ou NaCl 0,9%, 100 à 200 mg/mL.", 
        dilution: "Dans G5% ou NaCl 0,9%.", 
        administration:"IVL en 30 minutes. ", 
        remarques:"",
        lien: "https://www.vidal.fr/medicaments/substances/cefepime-6916.html",
       },
     
        { 
        isShown:false, 
        title: "Céfotaxime (Claforan®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "C3G", 
        voieAdmin: "IV",       
        presentation: "CEFOTAXIME (sel de na) 500 mg pdre p sol inj",
        posologie: "100 à 200 mg/kg/j, 300 mg/kg/j dans les infections méningées, en 3 à 4 prises, sans dépasser 24g/j.", 
        reconstitution: "EPPI 10 mL.", 
        dilution: "G5% ou NaCl 0,9%, 10 à 50 mg/mL, ne pas dépasser 150 mg/mL pour l'administration IV.", 
        administration:"IVL en 20 à 60 minutes.", 
        remarques:"Risque d'arythmie cardiaque en cas d'administration intraveineuse rapide sur cathéter veineux central.",
        lien: "https://www.vidal.fr/medicaments/substances/cefotaxime-861.html",
       },
     
        { 
        isShown:false, 
        title: "Ceftazidime (Fortum®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "C4G", 
        voieAdmin: "IV",       
        presentation: "CEFTAZIDIME 250 mg pdre p sol inj",
        posologie: "50 à 200 mg/kg/j en 3 prises ou en continu, sans dépasser 6 g/j.", 
        reconstitution: "G5% ou NaCl 0,9%, 10mL.", 
        dilution: "G5% ou NaCl 0,9%, stable 18h si concentration < 40 mg/mL, ne pas dépasser 180 mg/mL de concentration en cas de restriction hydrique.", 
        administration:"IVL sur 30 minutes ou IVSE continue.", 
        remarques:"Incompatible avec le bicarbonate, l'aciclovir et le ganciclovir.",
        lien: "https://www.vidal.fr/medicaments/gammes/fortum-3888.html",
      },
     
        { 
        isShown:false, 
        title: "Ceftriaxone (Rocéphine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "C3G", 
        voieAdmin: "IV",       
        presentation: "CEFTRIAXONE (sodique) 1 g/10 ml pdre/solv p sol inj ",
        posologie: "50 à 100 mg/kg/j en 1 prise, sans dépasser 4g/j.", 
        reconstitution: "EPPI, G5% ou NaCl 0,9%, 100 mg/mL.", 
        dilution: "G5% ou NaCl 0,9%, 10 à 40 mg/mL.", 
        administration:"IVL sur 30 minutes.", 
        remarques:"Incompatible avec le calcium, la vancomycine, le fluconazole, les aminosides, la nutrition parentérale. Contre indiqué avant 28j et en cas d'administration de calcium IV associée. Coloration jaune normale.",
        lien: "https://www.vidal.fr/medicaments/gammes/rocephine-8900.html", 
      },
     
        { 
        isShown:false, 
        title: "Ciprofloxacine (Ciflox®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Fluoroquinolones", 
        voieAdmin: "IV",       
        presentation: "CIPROFLOXACINE (sulfate) 2 mg/ml sol p perf",
        posologie: "20 à 30 mg/kg/j - 45 mg/kg/j chez le drépanocytaire - en 2 à 3 prises, sans dépasser 1,2 g/j.", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVL sur 60 minutes.", 
        remarques:"Incompatible avec la nutrition parentérale, les pénicillines, les héparines, les solutions alcalines. Privilégier la voie orale : la biodisponibilité est identique.",
        lien: "https://www.vidal.fr/medicaments/gammes/ciflox-1909.html",
      },
     
        { 
        isShown:false, 
        title: "Clindamycine (Dalacine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Lincosamide", 
        voieAdmin: "IV",       
        presentation: "CLINDAMYCINE (phosphate) 600 mg/4 ml sol inj",
        posologie: "30 à 40 mg/kg/j en 3 à 4 prises, sans dépasser 2,4 g/j.", 
        reconstitution: "NA.", 
        dilution: "G5% ou NaCl 0,9%, max. 18 mg/mL.", 
        administration:"IVL en 30 minutes, ne pas dépasser 20 mg/kg/h ou 30 mg/min.", 
        remarques:"Incompatible avec l'ampicilline, la phénytoïne, les barbituriques, l'aminophylline, le calcium, le magnésium, la ceftriaxone, la ciprofloxacine et la ranitidine.",
        lien: "https://www.vidal.fr/medicaments/gammes/dalacine-2500.html",
      },
     
        { 
        isShown:false, 
        title: "Cloxacilline (Orbénine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "CLOXACILLINE (sodique) 1 g pdre p sol inj",
        posologie: "100 à 200 mg/kg/j en 4 à 6 prises, max. 12 g/j.", 
        reconstitution: "EPPI, G5% ou NaCl 0,9%, 1g dans 16 mL.", 
        dilution: "G5% ou NaCl 0,9%, 10 mg/mL.", 
        administration:"IVL sur 60 minutes.", 
        remarques:"Incompatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/gammes/orbenine-7195.html",
      },
    
        { 
        isShown:false, 
        title: "Fluconazole (Triflucan®)", 
        AMM:"", 
        indication: "Antifongiques", 
        classeMed: "Azolés", 
        voieAdmin: "IV",       
        presentation: "FLUCONAZOLE 2 mg/ml sol p perf",
        posologie: "3 à 12 mg/kg/j en 1 prise.", 
        reconstitution: "", 
        dilution: "", 
        administration:"IVL en 30 minutes, 120 minutes si > 6 mg/kg/j.", 
        remarques:"Inhibiteur enzymatique. Teneur en sodium significative à 0,155 mEq/mL.",
        lien: "https://www.vidal.fr/medicaments/gammes/triflucan-10578.html", 
      },
     
        { 
        isShown:false, 
        title: "Fosfomycine (Fosfocine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Antibactérien", 
        voieAdmin: "IV",       
        presentation: "FOSFOMYCINE (disodique) 1 g pdre p sol p perf ",
        posologie: "100 à 200 mg/kg/j en 2 à 4 prises, sans dépasser 16 g/j.", 
        reconstitution: "1g avec 10 mL d'EPPI. 4g avec 15 mL d'EPPI.", 
        dilution: "G5% ou NaCl 0,9%, max. 10 mg/mL.", 
        administration:"IVL en 60 minutes.", 
        remarques:"Apports en sodium significatifs à 14,3 mEq/g.",
        lien: "https://www.vidal.fr/medicaments/substances/fosfomycine-1547.html", 
      },
      
        { 
        isShown:false, 
        title: "Gentamicine (Gentalline®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Aminoside", 
        voieAdmin: "IV",       
        presentation: "GENTAMICINE (sulfate) 40 mg/2 ml sol inj",
        posologie: "5 à 8 mg/kg/j en 1 prise.", 
        reconstitution: "NA.", 
        dilution: "G5% ou NaCl 0,9%, max. 10 mg/mL.", 
        administration:"IVL en 30 minutes.", 
        remarques:"Objectifs : pic 60 à 80 mg/L, résiduelle inférieure à 1 mg/L. Incompatible avec les pénicillines et les héparines > 1 UI/mL.",
        lien: "https://www.vidal.fr/medicaments/substances/gentamicine-1610.html",
       },
     
        { 
        isShown:false, 
        title: "Imipénème-Cilastine (Tienam®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "CILASTATINE (sodique) 500 mg + IMIPENEM 500 mg pdre p sol p perf",
        posologie: "60 à 100 mg/kg/j en 4 prises sans dépasser 4 g/j.", 
        reconstitution: "G5% ou NaCl 0,9%, 25 mg/mL.", 
        dilution: "G5% ou NaCl 0,9%, 5 mg/mL, max. 7 mg/mL si restriction hydrique, stable 4h.", 
        administration:"IVL en 30 minutes, 60 minutes au delà de 500 mg.",
        remarques:"Posologies et concentrations exprimées en dose d'Imipgène. Contre indique chez l'insuffisant rénale. Compatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/gammes/tienam-10335.html", 
      },

      { 
        isShown:false, 
        title: "Lévofloxacine (Tavanic®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Fluoroquinolones", 
        voieAdmin: "IV",       
        presentation: "LEVOFLOXACINE 5 mg/ml sol p perf ",
        posologie: "20 mg/kg/j de 6 mois à 5 ans, en 2 prises. 10 mg/kg/j au delà de 5 ans, en 1 prise, sans dépasser 1g/j.",
        reconstitution: "", 
        dilution: "", 
        administration:"IVL en 60 minutes.", 
        remarques:"Incompatible avec les bicarbonates et les héparines. Privilégier la voie orale : la biodisponibilité est identique.",
        lien: "https://www.vidal.fr/medicaments/gammes/tavanic-17333.html",
       },

      { 
        isShown:false, 
        title: "Méropénème (Meronem®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "MEROPENEM 1 g pdre p sol inj/p perf ",
        posologie: "60 à 120 mg/kg/j en 3 prises ou en continu, sans dépasser 6 g/j.", 
        reconstitution: "EPPI ou NaCl 0,9%, 50 mg/mL.", 
        dilution: "NaCl 0,9% (stable 8h) ou G5% (stable 2h), 1 à 20 mg/mL.", 
        administration:"IVL en 30 minutes.", 
        remarques:"Compatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/meronem-1-g-pdre-p-sol-inj-p-perf-10764.html",
       },

      { 
        isShown:false, 
        title: "Métronidazole (Flagyl®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Imidazolés", 
        voieAdmin: "IV",       
        presentation: "METRONIDAZOLE 0,5 % sol p perf",
        posologie: "30 mg/kg/j en 3 à 4 prises, sans dépasser 4 g/j.", 
        reconstitution: "NA.", 
        dilution: "NA.", 
        administration:"IVL en 30 minutes.", 
        remarques:"Compatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/gammes/flagyl-3734.html", 
      },

      { 
        isShown:false, 
        title: "Pipéracilline-Tazobactam (Tazocilline®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "PIPERACILLINE (sodique) 2 g + TAZOBACTAM (sodique) 250 mg pdre p sol inj",
        posologie: "300 mg/kg/j, en 3 à 4 prises ou en continu, sans dépasser 16 g/j.", 
        reconstitution: "EPPI, G5% ou NaCl 0,9%, 200 mg/mL.", 
        dilution: "G5 ou NaCl 0,9%, 20 à 80 mg/mL, stable 24h.", 
        administration:"IVL en 30 minutes.", 
        remarques:"Posologies et concentrations exprimées en pipéracilline. Incompatible avec les aminosides et les bicarbonates. Compatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/tazocilline-2-g-0-25-g-pdre-p-sol-p-perf-127614.html",
      },

      { 
        isShown:false, 
        title: "Rifampicine (Rifadine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Anti-tuberculeux", 
        voieAdmin: "IV",       
        presentation: "RIFAMPICINE (sel de na) 600 mg/10 ml pdre/solv p sol diluer p perf",
        posologie: "10 à 30 mg/kg/j en 1 prise (tuberculose) ou 2 prises (autres indications), sans dépasser 1,2 g/j.", 
        reconstitution: "EPPI 60 mg/mL.", 
        dilution: "G5% ou NaCl 0,9%, usuel 2,4 mg/mL, ne pas dépasser 6 mg/mL, stable 6h.", 
        administration:"IVL en 30 minutes.", 
        remarques:"Incompatible avec la nutrition parentérale. Très agressif en cas d'extravasation. Inducteur enzymatique.",
        lien: "https://www.vidal.fr/medicaments/gammes/rifadine-8827.html",
      },

      { 
        isShown:false, 
        title: "Ticarcilline-Acide Clavulanique (Claventin®, Timentin®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "β-lactamine", 
        voieAdmin: "IV",       
        presentation: "TIMENTIN 3,2 g pdre p sol inj",
        posologie: "225 à 300 mg/kg/j en 3 à 4 prises, sans dépasser 18 g/j.", 
        reconstitution: "EPPI ou NaCl 0,9%.", 
        dilution: "G5% ou NaCl 0,9%, 30 à 50 mg/mL, stable 6h.", 
        administration:"IVL sur 30 minutes.", 
        remarques:"Posologies et concentrations exprimées en ticarcilline. Max 5 mg/kg/prise et 20 mg/kg/j d'acide clavulanique. Incompatible avec les aminosideS, bicarbonates et la nutrition parentérale. Teneur en sodium 5,2 mEq/g et teneur en potassium 0,33 mEq/g. ",
        lien: "https://www.vidal.fr/medicaments/substances/ticarcilline-3998.html",
       },

      { 
        isShown:false, 
        title: "Triméthoprime-Sulfaméthoxazole (Bactrim®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Sulfamide", 
        voieAdmin: "IV",       
        presentation: "SULFAMETHOXAZOLE 400 mg/5 ml + TRIMETHOPRIME 80 mg/5 ml sol diluer p perf",
        posologie: "30 à 60 mg/kg/j en 2 prises (curatif pneumocystis carinii : 100 mg/kg/j en 3 prises).", 
        reconstitution: "", 
        dilution: "G5% ou NaCl 0,9% 3,2 mg/mL (stable 6h), max. 8 mg/mL si restriction hydrique (stable 1h).", 
        administration:"IVL sur 60 minutes.", 
        remarques:"Posologies et concentrations exprimées en Sulfaméthoxazole. Peut être administré pur sur VVC. Incompatible avec la nutrition parentérale.",
        lien: "https://www.vidal.fr/medicaments/gammes/bactrim-897.html",
       },

      { 
        isShown:false, 
        title: "Vancomycine (Vancocine®)", 
        AMM:"", 
        indication: "Antibiothérapie", 
        classeMed: "Glycopeptide", 
        voieAdmin: "IV",       
        presentation: "VANCOMYCINE (chlorhydrate) 250 mg pdre p sol diluer p perf ",
        posologie: "40 à 60 mg/kg/j en 4 prises ou en continu.", 
        reconstitution: "EPPI 50 mg/mL.", 
        dilution: "G5% ou NaCl 0,9%, ne pas dépasser 10 mg/mL, stable 24h.", 
        administration:"IVL en 60 minutes ou IVSE.", 
        remarques:"Objectif : T0 20-25 mg/mL. Ralentir la perfusion en cas de réaction cutanée (Redman Syndrome). Compatible avec la nutrition parentérale, les lipides IV et l'héparine < 1 UI/mL.",
        lien: "https://www.vidal.fr/medicaments/substances/vancomycine-6898.html", 
      },

    ];

  }

  orderCards(){

    const sorted = this.cards.sort((a, b) => a.title > b.title ? 1 : -1);
    const grouped = sorted.reduce((groups, card) => {
    const letter = card.title.charAt(0);

    groups[letter] = groups[letter] || [];
    groups[letter].push(card);

      return groups;}, {});

    const result = Object.keys(grouped).map(key => ({key, cards: grouped[key]}));
};

  filterTitles(searchTerm) {
   return  this.cards.filter(item => {
      return item.title
       .toLowerCase().indexOf(searchTerm.toLowerCase()) > -1 ;
    });
  } 


};